// Generated by npm run xdr:build. Edit decide-source.mjs and patterns.json.

// xdr/web-injection/patterns.json
var patterns_default = [
  { name: "sql_injection", condition: "\uC694\uCCAD\uC758 SQL \uC5F0\uACB0\xB7\uC870\uAC74 \uAD6C\uBB38 \uB610\uB294 \uC13C\uC11C\uAC00 \uAC80\uCD9C\uD55C SQL \uC8FC\uC785 \uAD6C\uC870\uAC00 \uAC19\uC740 \uC8FC\uC18C\uC5D0\uC11C 5\uAC74 \uC774\uC0C1, \uC218\uC900 10 \uC774\uC0C1; \uB2E8\uC21C \uC218\uC5C5 \uB2E8\uC5B4\uB294 \uC81C\uC678", minCount: 5, minLevel: 10, evidence: "MITRE ATT&CK T1190\uC758 \uACF5\uAC1C \uC571 \uC545\uC6A9 \uD0D0\uC9C0\uC5D0 \uD574\uB2F9\uD558\uB294 \uC785\uB825 \uC870\uC791 \uC2E0\uD638\uB2E4. \uBC18\uBCF5 \uC784\uACC4\uAC12\uC740 \uD559\uC2B5 \uC815\uCC45\uC774\uB2E4.", source: "https://attack.mitre.org/techniques/T1190/" },
  { name: "script_injection", condition: "\uC2A4\uD06C\uB9BD\uD2B8 \uD0DC\uADF8\xB7\uC774\uBCA4\uD2B8 \uD578\uB4E4\uB7EC\xB7\uC2A4\uD06C\uB9BD\uD2B8 \uC0BD\uC785 \uC13C\uC11C \uACBD\uBCF4\uAC00 \uAC19\uC740 \uC8FC\uC18C\uC5D0\uC11C 5\uAC74 \uC774\uC0C1, \uC218\uC900 10 \uC774\uC0C1; \uC218\uC5C5\uBA85 script\uB294 \uC81C\uC678", minCount: 5, minLevel: 10, evidence: "\uACF5\uAC1C \uC571\uC758 \uC785\uB825 \uCC98\uB9AC \uCDE8\uC57D\uC810 \uC545\uC6A9\uC774\uB77C\uB294 T1190 \uBC94\uC8FC\uC5D0\uC11C \uC0BD\uC785 \uAD6C\uBB38\uC744 \uC810\uAC80\uD55C\uB2E4. \uD0A4\uC6CC\uB4DC \uD558\uB098\uB9CC\uC73C\uB85C \uC545\uC6A9 \uC131\uACF5\uC744 \uB2E8\uC815\uD558\uC9C0 \uC54A\uB294\uB2E4.", source: "https://attack.mitre.org/techniques/T1190/" },
  { name: "path_traversal", condition: "../ \uB610\uB294 \uC13C\uC11C\uC758 \uACBD\uB85C \uC774\uD0C8\xB7\uAC70\uC2AC\uB7EC \uC62C\uB77C\uAC00\uAE30 \uACBD\uBCF4\uAC00 \uAC19\uC740 \uC8FC\uC18C\uC5D0\uC11C 5\uAC74 \uC774\uC0C1, \uC218\uC900 10 \uC774\uC0C1", minCount: 5, minLevel: 10, evidence: "T1190\uC740 \uACF5\uAC1C \uC571 \uCDE8\uC57D\uC810 \uC545\uC6A9\uC744 \uB2E4\uB8EC\uB2E4. \uACBD\uB85C \uC774\uD0C8\uC740 \uC774 \uD559\uC2B5 \uACBD\uBCF4\uC758 \uC785\uB825 \uC870\uC791 \uC2E0\uD638\uC774\uBA70 \uC2E4\uC81C \uD30C\uC77C \uC720\uCD9C \uC99D\uAC70\uC640 \uAD6C\uBD84\uD55C\uB2E4.", source: "https://attack.mitre.org/techniques/T1190/" },
  { name: "command_injection", condition: "\uBA85\uB839 \uAD6C\uBD84\uC790\uC640 \uBA85\uB839 \uAD6C\uC870 \uB610\uB294 \uC13C\uC11C\uC758 \uBA85\uB839 \uAD6C\uBD84\uC790 \uBC18\uBCF5 \uACBD\uBCF4\uAC00 \uAC19\uC740 \uC8FC\uC18C\uC5D0\uC11C 5\uAC74 \uC774\uC0C1, \uC218\uC900 10 \uC774\uC0C1", minCount: 5, minLevel: 10, evidence: "T1190\uC758 \uACF5\uAC1C \uC571 \uC545\uC6A9 \uBC94\uC8FC\uC5D0 \uC18D\uD558\uB294 \uBA85\uB839 \uC8FC\uC785 \uAD6C\uC870\uB97C \uC810\uAC80\uD55C\uB2E4. \uBA85\uB839\uC740 \uC2E4\uD589\uD558\uC9C0 \uC54A\uC73C\uBA70 \uC784\uACC4\uAC12\uC740 \uD559\uC2B5 \uC815\uCC45\uC774\uB2E4.", source: "https://attack.mitre.org/techniques/T1190/" }
];

// xdr/classify-alert.mjs
function classifyAlert(alert) {
  const candidate = String(alert?.data?.srcip ?? "");
  let sourceIp = null;
  if (/^\d{1,3}(?:\.\d{1,3}){3}$/u.test(candidate) && candidate.split(".").every((part) => Number(part) <= 255 && String(Number(part)) === part)) sourceIp = candidate;
  else if (/^[a-f\d:]+$/iu.test(candidate) && candidate.includes(":")) {
    try {
      if (new URL(`http://[${candidate}]/`).hostname) sourceIp = candidate;
    } catch {
    }
  }
  const time = Date.parse(alert?.timestamp);
  return {
    timestamp: Number.isFinite(time) ? new Date(time).toISOString() : null,
    sourceIp,
    level: Number.isInteger(alert?.rule?.level) ? alert.rule.level : 0,
    // Descriptions are used only for classification; reason never echoes them.
    description: String(alert?.rule?.description ?? "").slice(0, 2e3)
  };
}

// xdr/jev.mjs
var reviewer;
function setJevReviewer(next) {
  reviewer = typeof next === "function" ? next : void 0;
}
async function reviewAmbiguous({ pattern, level, count }) {
  if (!reviewer) return null;
  let timer;
  try {
    const response = await Promise.race([
      Promise.resolve().then(() => reviewer({ pattern, level, count })),
      new Promise((resolve) => {
        timer = setTimeout(() => resolve(null), 1e3);
      })
    ]);
    const confidence = response?.confidence;
    return typeof confidence === "number" && Number.isFinite(confidence) && confidence >= 0 && confidence <= 1 ? confidence : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}
function decision(confidence, reason) {
  return { action: confidence >= 0.85 ? "block" : confidence >= 0.5 ? "alert" : "record", confidence, reason };
}
async function ambiguous(pattern, level, count) {
  const confidence = await reviewAmbiguous({ pattern, level, count });
  return decision(confidence ?? 0.5, `${pattern}: ${confidence === null ? "Jev unavailable; alert fallback" : "Jev confidence"}`);
}

// xdr/web-injection/decide-source.mjs
async function decide(alert) {
  const row = classifyAlert(alert);
  if (!row.timestamp || !row.sourceIp) return decision(0.5, "web_unconfirmed: invalid event; alert only");
  const text = row.description;
  let url = String(alert?.data?.url ?? "").slice(0, 4096);
  for (let i = 0; i < 2; i++) {
    try {
      url = decodeURIComponent(url);
    } catch {
      break;
    }
  }
  const signals = [
    /SQL\s*(?:구문|표식)|데이터베이스 조회를 이어|sql injection/iu.test(text) || /\bunion\s+(?:all\s+)?select\b|\bor\s+['"\d]+\s*=\s*['"\d]+/iu.test(url),
    /스크립트\s*(?:삽입|표식)|script injection/iu.test(text) || /<script\b|on(?:error|load)\s*=|javascript\s*:/iu.test(url),
    /경로.{0,15}(?:거슬러|이탈)|path traversal/iu.test(text) || /\.\.\//u.test(url),
    /명령 구분자|command injection/iu.test(text) || /(?:;|\|\||&&)\s*(?:cat|id|whoami|curl|wget)\b/iu.test(url)
  ];
  const count = Math.max(0, Number(alert?.data?.count) || 0);
  const index = signals.findIndex(Boolean);
  if (index >= 0 && count >= patterns_default[index].minCount && row.level >= patterns_default[index].minLevel) {
    return decision(0.96, `${patterns_default[index].name}: corroborated repeated injection attempts`);
  }
  if (index >= 0 || row.level >= 5) return ambiguous(index >= 0 ? patterns_default[index].name : "web_unconfirmed", row.level, count);
  return decision(0.1, "web_normal: no corroborated attack pattern");
}
export {
  decide,
  setJevReviewer
};
