import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

for (const key of ['brute-force', 'web-injection']) {
  await build({
    entryPoints: [fileURLToPath(new URL(`../xdr/${key}/decide-source.mjs`, import.meta.url))],
    outfile: fileURLToPath(new URL(`../xdr/${key}/decide.mjs`, import.meta.url)),
    bundle: true, platform: 'neutral', format: 'esm', target: 'es2022',
    banner: { js: '// Generated by npm run xdr:build. Edit decide-source.mjs and patterns.json.' },
  });
}
console.log('두 제출용 decide.mjs를 외부 import 없이 생성했습니다.');
