// Generated by npm run xdr:build. Edit decide-source.mjs and patterns.json.

// xdr/brute-force/patterns.json
var patterns_default = [
  { name: "auth_failure_burst", condition: "\uAC19\uC740 \uCD9C\uBC1C \uC8FC\uC18C\xB7\uACC4\uC815\uC758 \uC9D1\uACC4 \uB85C\uADF8\uC778 \uC2E4\uD328 20\uAC74 \uC774\uC0C1, 5\uBD84 \uC774\uB0B4 \uB610\uB294 \uC13C\uC11C\uC758 \uC5F0\uC18D \uC2E4\uD328 \uACBD\uBCF4, \uC218\uC900 10 \uC774\uC0C1; \uB2E8\uC77C \uC2E4\uD328 \uBC0F \uC131\uACF5\uC740 \uC81C\uC678", minCount: 20, maxWindowSeconds: 300, minLevel: 10, evidence: "MITRE ATT&CK T1110\uC740 \uBC18\uBCF5\uC801\uC778 \uBE44\uBC00\uBC88\uD638 \uCD94\uCE21\uC744 \uC124\uBA85\uD55C\uB2E4. \uC218\uCE58 \uC784\uACC4\uAC12\uC740 \uC774 \uD559\uC2B5 \uC815\uCC45\uC758 \uC124\uC815\uC774\uB2E4.", source: "https://attack.mitre.org/techniques/T1110/" },
  { name: "password_spray", condition: "\uAC19\uC740 \uCD9C\uBC1C \uC8FC\uC18C\uC5D0\uC11C 5\uAC1C \uC774\uC0C1 \uACC4\uC815\uC5D0 \uAC19\uC740 \uBE44\uBC00\uBC88\uD638 \uB610\uB294 \uC77C\uC815\uD55C \uAC04\uACA9\uC758 \uC2E4\uD328\uAC00 \uC9D1\uACC4\uB428; \uC218\uC900 10 \uC774\uC0C1\uC774\uBA70 \uC21C\uD68C \uADFC\uAC70\uAC00 \uD544\uC694", minAccounts: 5, minCount: 10, minLevel: 10, evidence: "MITRE ATT&CK T1110.003\uC740 \uC5EC\uB7EC \uACC4\uC815\uC5D0 \uBE44\uBC00\uBC88\uD638\uB97C \uB300\uC785\uD558\uB294 password spraying\uC744 \uC124\uBA85\uD55C\uB2E4. \uACBD\uBCF4\uC5D0 \uBE44\uBC00\uBC88\uD638 \uC6D0\uBB38\uC740 \uD544\uC694\uD558\uC9C0 \uC54A\uB2E4.", source: "https://attack.mitre.org/techniques/T1110/003/" }
];

// xdr/classify-alert.mjs
function classifyAlert(alert) {
  const candidate = String(alert?.data?.srcip ?? "");
  let sourceIp = null;
  if (/^\d{1,3}(?:\.\d{1,3}){3}$/u.test(candidate) && candidate.split(".").every((part) => Number(part) <= 255 && String(Number(part)) === part)) sourceIp = candidate;
  else if (/^[a-f\d:]+$/iu.test(candidate) && candidate.includes(":")) {
    try {
      if (new URL(`http://[${candidate}]/`).hostname) sourceIp = candidate;
    } catch {
    }
  }
  const time = Date.parse(alert?.timestamp);
  return {
    timestamp: Number.isFinite(time) ? new Date(time).toISOString() : null,
    sourceIp,
    level: Number.isInteger(alert?.rule?.level) ? alert.rule.level : 0,
    // Descriptions are used only for classification; reason never echoes them.
    description: String(alert?.rule?.description ?? "").slice(0, 2e3)
  };
}

// xdr/jev.mjs
var reviewer;
function setJevReviewer(next) {
  reviewer = typeof next === "function" ? next : void 0;
}
async function reviewAmbiguous({ pattern, level, count }) {
  if (!reviewer) return null;
  let timer;
  try {
    const response = await Promise.race([
      Promise.resolve().then(() => reviewer({ pattern, level, count })),
      new Promise((resolve) => {
        timer = setTimeout(() => resolve(null), 1e3);
      })
    ]);
    const confidence = response?.confidence;
    return typeof confidence === "number" && Number.isFinite(confidence) && confidence >= 0 && confidence <= 1 ? confidence : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}
function decision(confidence, reason) {
  return { action: confidence >= 0.85 ? "block" : confidence >= 0.5 ? "alert" : "record", confidence, reason };
}
async function ambiguous(pattern, level, count) {
  const confidence = await reviewAmbiguous({ pattern, level, count });
  return decision(confidence ?? 0.5, `${pattern}: ${confidence === null ? "Jev unavailable; alert fallback" : "Jev confidence"}`);
}

// xdr/brute-force/decide-source.mjs
async function decide(alert) {
  const row = classifyAlert(alert);
  if (!row.timestamp || !row.sourceIp) return decision(0.5, "auth_failure_burst: invalid event; alert only");
  const text = row.description;
  const count = Math.max(0, Number(alert?.data?.count) || 0);
  const accounts = new Set(String(alert?.data?.accounts ?? "").split(",").filter(Boolean)).size;
  const failure = /(?:로그인|비밀번호|인증).{0,25}실패|실패.{0,25}(?:로그인|비밀번호)|failed (?:password|login)|authentication fail/iu.test(text);
  const spray = /여러 계정|계정\s*\d+개|서로 다른 계정|계정 이름을 바꿔|password spray/iu.test(text);
  const repeated = /연속|이어졌|쌓였|실패.{0,4}\d+건|failures|attempts/iu.test(text);
  const window = text.match(/(\d+)\s*분\s*(?:안|동안)/u);
  const withinWindow = !window || Number(window[1]) * 60 <= patterns_default[0].maxWindowSeconds;
  if (row.level >= patterns_default[1].minLevel && spray && (accounts >= patterns_default[1].minAccounts && /같은 비밀번호|연속|일정한 간격/iu.test(text) || failure && count >= patterns_default[1].minCount)) {
    return decision(0.96, "password_spray: repeated failures across accounts");
  }
  if (failure && repeated && withinWindow && row.level >= patterns_default[0].minLevel && count >= patterns_default[0].minCount) {
    return decision(0.96, "auth_failure_burst: repeated failures within sensor window");
  }
  if (failure && count > 1 || spray || row.level >= 5) return ambiguous(spray ? "password_spray" : "auth_failure_burst", row.level, count);
  return decision(0.1, "auth_normal: no corroborated attack pattern");
}
export {
  decide,
  setJevReviewer
};
